### PR TITLE
Fixed unzipping mods causing materials not to load

### LINKED ISSUE #523: Unzipping terrain causes materials not to load
If you unzip a terrain the materials will not load

zipped

unzipped

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Fixes #523

### CODE REVIEW

File: source/main/resources/CacheSystem.cpp [hunk 1]
```diff
@@ -1106,7 +1106,9 @@ bool CacheSystem::CheckResourceLoaded(Ogre::String & filename, Ogre::String& gro
     if (ResourceGroupManager::getSingleton().resourceExistsInAnyGroup(filename))
     {
         group = ResourceGroupManager::getSingleton().findGroupContainingResource(filename);
-        return true;
+        // Files are not allowed to be loaded from the Content resource group, except odef files
+        if(group != "Content" || filename.find("odef") != std::string::npos)
```
Comment (only-a-ptr) [inline source/main/resources/CacheSystem.cpp]: Umm, neat hack.

I can't recall why we have both CONTENT_RG "Content" + TEMP_RG "Temp" while both are only used during cache regen. I think CONTENT_RG should be destroyed afterwards, in which case we wouldn't need this check.

File: source/main/resources/CacheSystem.cpp [hunk 2]
```diff
@@ -1138,8 +1140,7 @@ void CacheSystem::LoadResource(CacheEntry& t)
         return;
     }
 
-    static int rg_counter = 0;
-    String group = "Mod-" + std::to_string(rg_counter++);
+    String group = t.fname;
```
Comment (only-a-ptr) [inline source/main/resources/CacheSystem.cpp]: Well, there's non-zero chance this will cause conflicts, I can imagine thins like `woodenbox.load`

**Comment by tritonas00** [comment]
seems to work fine!
